<?php

namespace Proxies\__CG__\follow_the_rhythm\SymfonyBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Utilisateur extends \follow_the_rhythm\SymfonyBundle\Entity\Utilisateur implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'follow_the_rhythm\\SymfonyBundle\\Entity\\Utilisateur' . "\0" . 'id', '' . "\0" . 'follow_the_rhythm\\SymfonyBundle\\Entity\\Utilisateur' . "\0" . 'pseudo', '' . "\0" . 'follow_the_rhythm\\SymfonyBundle\\Entity\\Utilisateur' . "\0" . 'mdp', '' . "\0" . 'follow_the_rhythm\\SymfonyBundle\\Entity\\Utilisateur' . "\0" . 'nbSignalement', '' . "\0" . 'follow_the_rhythm\\SymfonyBundle\\Entity\\Utilisateur' . "\0" . 'artiste', '' . "\0" . 'follow_the_rhythm\\SymfonyBundle\\Entity\\Utilisateur' . "\0" . 'concert', '' . "\0" . 'follow_the_rhythm\\SymfonyBundle\\Entity\\Utilisateur' . "\0" . 'moderateur', '' . "\0" . 'follow_the_rhythm\\SymfonyBundle\\Entity\\Utilisateur' . "\0" . 'UsersIAdd', '' . "\0" . 'follow_the_rhythm\\SymfonyBundle\\Entity\\Utilisateur' . "\0" . 'myFriends');
        }

        return array('__isInitialized__', '' . "\0" . 'follow_the_rhythm\\SymfonyBundle\\Entity\\Utilisateur' . "\0" . 'id', '' . "\0" . 'follow_the_rhythm\\SymfonyBundle\\Entity\\Utilisateur' . "\0" . 'pseudo', '' . "\0" . 'follow_the_rhythm\\SymfonyBundle\\Entity\\Utilisateur' . "\0" . 'mdp', '' . "\0" . 'follow_the_rhythm\\SymfonyBundle\\Entity\\Utilisateur' . "\0" . 'nbSignalement', '' . "\0" . 'follow_the_rhythm\\SymfonyBundle\\Entity\\Utilisateur' . "\0" . 'artiste', '' . "\0" . 'follow_the_rhythm\\SymfonyBundle\\Entity\\Utilisateur' . "\0" . 'concert', '' . "\0" . 'follow_the_rhythm\\SymfonyBundle\\Entity\\Utilisateur' . "\0" . 'moderateur', '' . "\0" . 'follow_the_rhythm\\SymfonyBundle\\Entity\\Utilisateur' . "\0" . 'UsersIAdd', '' . "\0" . 'follow_the_rhythm\\SymfonyBundle\\Entity\\Utilisateur' . "\0" . 'myFriends');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Utilisateur $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setPseudo($pseudo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPseudo', array($pseudo));

        return parent::setPseudo($pseudo);
    }

    /**
     * {@inheritDoc}
     */
    public function getPseudo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPseudo', array());

        return parent::getPseudo();
    }

    /**
     * {@inheritDoc}
     */
    public function setMdp($mdp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMdp', array($mdp));

        return parent::setMdp($mdp);
    }

    /**
     * {@inheritDoc}
     */
    public function getMdp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMdp', array());

        return parent::getMdp();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbSignalement($nbSignalement)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbSignalement', array($nbSignalement));

        return parent::setNbSignalement($nbSignalement);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbSignalement()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbSignalement', array());

        return parent::getNbSignalement();
    }

    /**
     * {@inheritDoc}
     */
    public function addArtiste(\follow_the_rhythm\SymfonyBundle\Entity\Artiste $artiste)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addArtiste', array($artiste));

        return parent::addArtiste($artiste);
    }

    /**
     * {@inheritDoc}
     */
    public function removeArtiste(\follow_the_rhythm\SymfonyBundle\Entity\Artiste $artiste)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeArtiste', array($artiste));

        return parent::removeArtiste($artiste);
    }

    /**
     * {@inheritDoc}
     */
    public function getArtiste()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArtiste', array());

        return parent::getArtiste();
    }

    /**
     * {@inheritDoc}
     */
    public function addConcert(\follow_the_rhythm\SymfonyBundle\Entity\Concert $concert)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addConcert', array($concert));

        return parent::addConcert($concert);
    }

    /**
     * {@inheritDoc}
     */
    public function removeConcert(\follow_the_rhythm\SymfonyBundle\Entity\Concert $concert)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeConcert', array($concert));

        return parent::removeConcert($concert);
    }

    /**
     * {@inheritDoc}
     */
    public function getConcert()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConcert', array());

        return parent::getConcert();
    }

    /**
     * {@inheritDoc}
     */
    public function addUsersIAdd(\follow_the_rhythm\SymfonyBundle\Entity\Utilisateur $usersIAdd)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addUsersIAdd', array($usersIAdd));

        return parent::addUsersIAdd($usersIAdd);
    }

    /**
     * {@inheritDoc}
     */
    public function removeUsersIAdd(\follow_the_rhythm\SymfonyBundle\Entity\Utilisateur $usersIAdd)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeUsersIAdd', array($usersIAdd));

        return parent::removeUsersIAdd($usersIAdd);
    }

    /**
     * {@inheritDoc}
     */
    public function getUsersIAdd()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsersIAdd', array());

        return parent::getUsersIAdd();
    }

    /**
     * {@inheritDoc}
     */
    public function addMyFriend(\follow_the_rhythm\SymfonyBundle\Entity\Utilisateur $myFriend)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addMyFriend', array($myFriend));

        return parent::addMyFriend($myFriend);
    }

    /**
     * {@inheritDoc}
     */
    public function removeMyFriend(\follow_the_rhythm\SymfonyBundle\Entity\Utilisateur $myFriend)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeMyFriend', array($myFriend));

        return parent::removeMyFriend($myFriend);
    }

    /**
     * {@inheritDoc}
     */
    public function getMyFriends()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMyFriends', array());

        return parent::getMyFriends();
    }

    /**
     * {@inheritDoc}
     */
    public function setModerateur(\follow_the_rhythm\SymfonyBundle\Entity\Moderateur $moderateur = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setModerateur', array($moderateur));

        return parent::setModerateur($moderateur);
    }

    /**
     * {@inheritDoc}
     */
    public function getModerateur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getModerateur', array());

        return parent::getModerateur();
    }

}
