<?php

namespace follow_the_rhythm\SymfonyBundle\Repository;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;
use InvalidArgumentException;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

/**
 * ActualiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActualiteRepository extends \Doctrine\ORM\EntityRepository
{
    public function getActualiteArtiste(){
        //On recupère le gestionnaire d'entité
        $gestionnaireEntite=$this->_em;
        
        //On créé la requête
        $requete=$gestionnaireEntite->createQuery('SELECT ac,ar FROM follow_the_rhythmSymfonyBundle:Actualite ac LEFT JOIN ac.artiste ar');
        
        //On retourne le résultat de la requête
        return $requete->getResult();
    }
    
   /* public function getSearchList ($formvalue) 
	{
        $gestionnaireEntite=$this->_em;
        
        $requete=$gestionnaireEntite->createQuery('SELECT a FROM follow_the_rhythmSymfonyBundle:Actualite where a. LIKE :formvalue');
		$qb = $this->createQueryBuilder('a');
 
		$qb->where('a. LIKE :formvalue')
			  ->orWhere('a.process LIKE :formvalue')
			  ->setParameter('formvalue', '%'. $formvalue .'%');
		return $requete->getResult();
	}*/
    
    
    //fonction copiée/collée sur internet
     /**
     * Récupère une liste d'actualités triés et paginés.
     *
     * @param int $page Le numéro de la page
     * @param int $nbMaxParPage Nombre maximum d'article par page     
     *
     * @throws InvalidArgumentException
     * @throws NotFoundHttpException
     *
     * @return Paginator
     */
    public function findAllPagineEtTrieDesc($page, $nbMaxParPage)
    {
        if (!is_numeric($page)) {
            throw new InvalidArgumentException(
                'La valeur de l\'argument $page est incorrecte (valeur : ' . $page . ').'
            );
        }

        if ($page < 1) {
            throw new NotFoundHttpException('La page demandée n\'existe pas');
        }

        if (!is_numeric($nbMaxParPage)) {
            throw new InvalidArgumentException(
                'La valeur de l\'argument $nbMaxParPage est incorrecte (valeur : ' . $nbMaxParPage . ').'
            );
        }
      
      /*   
         $gestionnaireEntite=$this->_em;
        //On créé la requête
        $requete=$gestionnaireEntite->createQuery('SELECT ar,ac FROM follow_the_rhythmSymfonyBundle:Artiste ar LEFT JOIN ar.actualite ac');
        
        //On définie la valeur de l'identifiant du concert dont on cherche l'artiste
    
        $query=$requete->getResult();
        //On retourne le résultat de la requête
        
    */
         $qb = $this->createQueryBuilder('a')
            ->where('CURRENT_DATE()+1 >= a.dateActualite')
            ->orderBy('a.dateActualite', 'DESC');
        
        $query = $qb->getQuery();

        
        $premierResultat = ($page - 1) * $nbMaxParPage;
        $query->setFirstResult($premierResultat)->setMaxResults($nbMaxParPage);
        $paginator = new Paginator($query);

        if ( ($paginator->count() <= $premierResultat) && $page != 1) {
            throw new NotFoundHttpException('La page demandée n\'existe pas.'); // page 404, sauf pour la première page
        }

        return $paginator;
    }
    
    public function findAllPagineEtTrieAsc($page, $nbMaxParPage)
    {
        if (!is_numeric($page)) {
            throw new InvalidArgumentException(
                'La valeur de l\'argument $page est incorrecte (valeur : ' . $page . ').'
            );
        }

        if ($page < 1) {
            throw new NotFoundHttpException('La page demandée n\'existe pas');
        }

        if (!is_numeric($nbMaxParPage)) {
            throw new InvalidArgumentException(
                'La valeur de l\'argument $nbMaxParPage est incorrecte (valeur : ' . $nbMaxParPage . ').'
            );
        }
        /*
         $gestionnaireEntite=$this->_em;
        //On créé la requête
        $requete=$gestionnaireEntite->createQuery('SELECT ar,ac FROM follow_the_rhythmSymfonyBundle:Artiste ar LEFT JOIN ar.actualite ac');
        
        //On définie la valeur de l'identifiant du concert dont on cherche l'artiste
    
        $query=$requete->getResult();
    */
        $qb = $this->createQueryBuilder('a')
            ->where('CURRENT_DATE()+1 >= a.dateActualite')
            ->orderBy('a.dateActualite', 'ASC');
        
        $query = $qb->getQuery();

        $premierResultat = ($page - 1) * $nbMaxParPage;
        $query->setFirstResult($premierResultat)->setMaxResults($nbMaxParPage);
        $paginator = new Paginator($query);

        if ( ($paginator->count() <= $premierResultat) && $page != 1) {
            throw new NotFoundHttpException('La page demandée n\'existe pas.'); // page 404, sauf pour la première page
        }

        return $paginator;
    }
    
}
    
    
    
    
    /*
        public function getActualiteUniquementArtiste(){
        //On recupère le gestionnaire d'entité
        $gestionnaireEntite=$this->_em;
        
        //On créé la requête
        $requete=$gestionnaireEntite->createQuery('SELECT a FROM follow_the_rhythmSymfonyBundle:Actualite a WHERE a.concert = NULL');
        
        //On retourne le résultat de la requête
        return $requete->getResult();
    }*/
