<?php

namespace follow_the_rhythm\SymfonyBundle\Repository;

use Doctrine\ORM\EntityRepository;
/**
 * ArtisteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArtisteRepository extends EntityRepository
{
    public function getActualitesDUnArtiste($id){
        //On recupère le GE
        $gestionnaireEntite = $this->_em;
        
        //Créer la requete
        $requete = $gestionnaireEntite->CreateQuery('SELECT ac FROM follow_the_rhythmSymfonyBundle:Actualite ac JOIN ac.artiste ar WHERE ar.id= :id');
        
        //On définie la valeur de l'identifiant de l'artiste dont on cherche les actualités
        $requete->setParameter('id',$id);
        
        //Onexecute la requete
        $tabActualites=$requete->getResult();
        
        //Retourner les résultats
        return $tabActualites;
        
    }
    
}