<?php

namespace follow_the_rhythm\SymfonyBundle\Repository;

/**
 * ConcertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConcertRepository extends \Doctrine\ORM\EntityRepository
{
   public function getConcertArtiste(){
        //On recupère le gestionnaire d'entité
        $gestionnaireEntite=$this->_em;
        
        //On créé la requête
        $requete=$gestionnaireEntite->createQuery('SELECT a,c FROM follow_the_rhythmSymfonyBundle:Artiste a LEFT JOIN a.concert c');
        
        //On définie la valeur de l'identifiant du concert dont on cherche l'artiste
        
        $artiste=$requete->getResult();
        //On retourne le résultat de la requête
        return $artiste;
    }
    

}
