<?php

namespace follow_the_rhythm\SymfonyBundle\Repository;

/**
 * TopicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TopicRepository extends \Doctrine\ORM\EntityRepository
{
    public function getSearchTopic($recherche) 
	{
        $gestionnaireEntite=$this->_em;
        
        $requete=$gestionnaireEntite->createQuery('SELECT t FROM follow_the_rhythmSymfonyBundle:Topic t where t.titre LIKE :recherche');
        $requete->setParameter('recherche','%'.$recherche.'%');
		return $requete->getResult();
	}
}
