<?php

namespace follow_the_rhythm\SymfonyBundle\Repository;

/**
 * UtilisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateurRepository extends \Doctrine\ORM\EntityRepository
{
     public function getArtisteDunUtilisateur($id){
        /*
        //On recupère le GE
        $gestionnaireEntite = $this->_em;
        
        //Créer la requete
        //$requete = $gestionnaireEntite->CreateQuery('SELECT artiste FROM follow_the_rhythmSymfonyBundle:Utilisateur JOIN Utilisateur.artiste WHERE Utilisateur.id= :id');
        $requete = $gestionnaireEntite->CreateQuery('SELECT a FROM follow_the_rhythmSymfonyBundle:Utilisateur WHERE utilisateur_artistes.utilisateur_id= :id)');
        
        //On définie la valeur de lidentifiant de lartiste dont on cherche les actualités
        $requete->setParameter('id',$id);
        
        //Onexecute la requete
        $tabArtistes=$requete->getResult();
        
        //Retourner les résultats
        return $tabArtistes;*/
        
    }
}
